"use client";
import {useCallback,useEffect,useMemo,useRef,useState} from "react";

const MAP:Record<string,string>={A:".-",B:"-...",C:"-.-.",D:"-..",E:".",F:"..-.",G:"--.",H:"....",I:"..",J:".---",K:"-.-",L:".-..",M:"--",N:"-.",O:"---",P:".--.",Q:"--.-",R:".-.",S:"...",T:"-",U:"..-",V:"...-",W:".--",X:"-..-",Y:"-.--",Z:"--..","0":"-----","1":".----","2":"..---","3":"...--","4":"....-","5":".....","6":"-....","7":"--...","8":"---..","9":"----.",".":".-.-.-",",":"--..--","?":"..--..","!":"-.-.--","'":".----.","/":"-..-.","(":"-.--.",")":"-.--.-","&":".-...",":":"---...",";":"-.-.-.","=":"-...-","+":".-.-.","-":"-....-","_":"..--.-",'"':".-..-.","$":"...-..-","@":".--.-."};
const REVERSE=Object.fromEntries(Object.entries(MAP).map(([k,v])=>[v,k]));
const textToMorse=(s:string)=>s.toUpperCase().split("").map(c=>c===" "?"/":MAP[c]||c).join(" ");
const morseToText=(s:string)=>s.trim().split(/\s+/).map(c=>c==="/"?" ":REVERSE[c]||"?").join("");
const isMorse=(s:string)=>s.trim().length>0&&/^[.\-\s/]+$/.test(s.trim());

type Entry={input:string;output:string;mode:string};
export default function MorseTool(){
  const [input,setInput]=useState("HELLO WORLD"); const [speed,setSpeed]=useState(18); const [frequency,setFrequency]=useState(700); const [theme,setTheme]=useState("dark"); const [toast,setToast]=useState(""); const [history,setHistory]=useState<Entry[]>([]); const [playing,setPlaying]=useState(false); const [lit,setLit]=useState(false); const timers=useRef<number[]>([]);
  const mode=isMorse(input)?"Morse → Text":"Text → Morse"; const output=useMemo(()=>isMorse(input)?morseToText(input):textToMorse(input),[input]); const signal=isMorse(input)?input:textToMorse(input);
  const note=(s:string)=>{setToast(s);window.setTimeout(()=>setToast(""),1800)};
  useEffect(()=>{const saved=localStorage.getItem("morse-history");if(saved)try{setHistory(JSON.parse(saved))}catch{};const savedTheme=localStorage.getItem("morse-theme");if(savedTheme)setTheme(savedTheme)},[]);
  useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem("morse-theme",theme)},[theme]);
  useEffect(()=>{if(!input.trim())return;const id=window.setTimeout(()=>{const entry={input,output,mode};setHistory(old=>{const next=[entry,...old.filter(e=>e.input!==input)].slice(0,5);localStorage.setItem("morse-history",JSON.stringify(next));return next})},800);return()=>clearTimeout(id)},[input,output,mode]);
  useEffect(()=>{const handler=(e:Event)=>{const value=(e.currentTarget as HTMLElement).dataset.example;if(value){setInput(value);document.querySelector("#translator")?.scrollIntoView({behavior:"smooth"})}};const buttons=document.querySelectorAll("[data-example]");buttons.forEach(b=>b.addEventListener("click",handler));return()=>buttons.forEach(b=>b.removeEventListener("click",handler))},[]);
  const clearTimers=()=>{timers.current.forEach(clearTimeout);timers.current=[];setLit(false);setPlaying(false)};
  useEffect(()=>clearTimers,[]);
  const sequence=useCallback(()=>{const unit=1200/speed;let time=0;const pulses:{start:number,duration:number}[]=[];for(const c of signal){if(c==="."||c==="-"){const d=c==="."?unit:unit*3;pulses.push({start:time,duration:d});time+=d+unit}else if(c===" ")time+=unit*2;else if(c==="/")time+=unit*6}return{unit,pulses,total:time}},[signal,speed]);
  const play=()=>{clearTimers();if(!signal.trim())return;const Ctx=window.AudioContext||window.webkitAudioContext;const ctx=new Ctx();const {pulses,total}=sequence();setPlaying(true);pulses.forEach(p=>{const osc=ctx.createOscillator(),gain=ctx.createGain();osc.frequency.value=frequency;gain.gain.setValueAtTime(.0001,ctx.currentTime+p.start/1000);gain.gain.exponentialRampToValueAtTime(.18,ctx.currentTime+p.start/1000+.008);gain.gain.setValueAtTime(.18,ctx.currentTime+(p.start+p.duration-8)/1000);gain.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+(p.start+p.duration)/1000);osc.connect(gain).connect(ctx.destination);osc.start(ctx.currentTime+p.start/1000);osc.stop(ctx.currentTime+(p.start+p.duration)/1000+.02)});timers.current.push(window.setTimeout(()=>setPlaying(false),total));};
  const flash=()=>{clearTimers();const {pulses,total}=sequence();setPlaying(true);pulses.forEach(p=>{timers.current.push(window.setTimeout(()=>setLit(true),p.start),window.setTimeout(()=>setLit(false),p.start+p.duration))});timers.current.push(window.setTimeout(()=>setPlaying(false),total))};
  const vibrate=()=>{if(!navigator.vibrate){note("Vibration isn't supported here");return}const {unit}=sequence();const pattern:number[]=[];for(const c of signal){if(c===".")pattern.push(unit,unit);else if(c==="-")pattern.push(unit*3,unit);else if(c===" ")pattern.push(unit*2);else if(c==="/")pattern.push(unit*6)}navigator.vibrate(pattern);note("Vibration started")};
  const download=()=>{const {pulses,total}=sequence();const rate=44100,length=Math.ceil((total+200)/1000*rate),data=new Float32Array(length);pulses.forEach(p=>{for(let i=Math.floor(p.start/1000*rate);i<Math.min(length,Math.floor((p.start+p.duration)/1000*rate));i++){const edge=Math.min(i-p.start/1000*rate,(p.start+p.duration)/1000*rate-i,220);data[i]=Math.sin(2*Math.PI*frequency*i/rate)*.35*Math.min(1,edge/220)}});const buf=new ArrayBuffer(44+data.length*2),v=new DataView(buf);const str=(o:number,s:string)=>[...s].forEach((c,i)=>v.setUint8(o+i,c.charCodeAt(0)));str(0,"RIFF");v.setUint32(4,36+data.length*2,true);str(8,"WAVEfmt ");v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,rate,true);v.setUint32(28,rate*2,true);v.setUint16(32,2,true);v.setUint16(34,16,true);str(36,"data");v.setUint32(40,data.length*2,true);data.forEach((x,i)=>v.setInt16(44+i*2,Math.max(-1,Math.min(1,x))*32767,true));const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([buf],{type:"audio/wav"}));a.download="morse2text.wav";a.click();URL.revokeObjectURL(a.href);note("WAV downloaded")};
  const copy=async()=>{await navigator.clipboard.writeText(output);note("Copied to clipboard")};
  const share=async()=>{const text=`${input} — ${output}`;if(navigator.share)await navigator.share({title:"Morse code",text,url:location.href});else{await navigator.clipboard.writeText(text);note("Share text copied")}};
  return <div className={`tool-card ${lit?"is-lit":""}`}>
    <div className="tool-top"><div><span className="live-dot"/> LIVE TRANSLATOR</div><button className="theme-toggle" onClick={()=>setTheme(theme==="dark"?"light":"dark")} aria-label="Toggle color theme">{theme==="dark"?"☀":"☾"}</button></div>
    <div className="tool-grid"><div className="input-side"><label><span>Your message</span><small>{mode} · Auto-detected</small></label><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&(e.ctrlKey||e.metaKey))play()}} placeholder="Type text or Morse code…" aria-label="Text or Morse code input"/><div className="input-bottom"><span>{input.length} characters</span><button onClick={()=>setInput("")}>Clear</button></div></div><div className="output-side"><label><span>Translation</span><small>Ready</small></label><output>{output||"Your translation appears here"}</output><div className="output-actions"><button onClick={copy}>▣ Copy</button><button onClick={share}>↗ Share</button></div></div></div>
    <div className="signal-panel"><div className="player"><button className="play" onClick={playing?clearTimers:play} aria-label={playing?"Stop audio":"Play Morse audio"}>{playing?"■":"▶"}</button><div><span>{playing?"Transmitting signal…":"Ready to transmit"}</span><div className="wave">{Array.from({length:28},(_,i)=><i key={i} style={{height:`${8+((i*13)%22)}px`}}/>)}</div></div></div><div className="controls"><label>Speed <b>{speed} WPM</b><input type="range" min="8" max="35" value={speed} onChange={e=>setSpeed(+e.target.value)}/></label><label>Tone <b>{frequency} Hz</b><input type="range" min="400" max="1000" step="50" value={frequency} onChange={e=>setFrequency(+e.target.value)}/></label></div><div className="generator-actions"><button onClick={flash}>✦ Flash</button><button onClick={vibrate}>≈ Vibrate</button><button className="download" onClick={download}>↓ Download WAV</button></div></div>
    {history.length>0&&<div className="history"><span>Recent</span>{history.slice(0,3).map((h,i)=><button key={i} onClick={()=>setInput(h.input)}><b>{h.input.slice(0,20)}</b><code>{h.output.slice(0,30)}</code></button>)}<button onClick={()=>{setHistory([]);localStorage.removeItem("morse-history")}}>Clear history</button></div>}
    {toast&&<div className="toast" role="status">✓ {toast}</div>}
  </div>
}

declare global{interface Window{webkitAudioContext:typeof AudioContext}}
