import Script from "next/script";
import Translator from "./components/Translator";
import { Footer, Header } from "./components/SiteChrome";

const faq = [
  ["What is Baybayin?", "Baybayin is an indigenous Philippine writing system used widely before and during the early Spanish colonial period. It is an abugida: each consonant carries an inherent a sound, while small marks called kudlit change that vowel to i/e or u/o. Modern writers often add a virama to cancel the vowel."],
  ["How does the Baybayin translator work?", "The translator reads Latin letters as sound groups, then maps each consonant-vowel syllable to its Baybayin equivalent. It recognizes the Tagalog ng sound, adds modern virama marks to final consonants, and preserves spaces, numbers, and punctuation. Everything runs privately in your browser."],
  ["Is Baybayin the same as Alibata?", "No. Alibata is a twentieth-century name coined from the first letters of the Arabic alphabet. Historical sources use names such as baybayin, meaning to spell or trace. Baybayin is the preferred term among historians, cultural workers, and script practitioners today."],
  ["Can I use Baybayin for tattoos?", "Yes, but verify the sound-based spelling before committing it to skin. Baybayin represents pronunciation rather than English spelling. Use our tattoo preview as a conversation starter, compare the Latin guide, and ask a knowledgeable reader or Filipino artist to review the final design."],
  ["How do I write my name in Baybayin?", "Say your name naturally, divide it into syllables, and write those sounds rather than copying every Latin letter. Maria becomes ma-ri-ya, while Grace may be adapted as g-rey-s. Use the translator, then inspect each character’s tooltip to understand the conversion."],
  ["What is the difference between Baybayin and Badlit?", "Baybayin usually refers to the Tagalog form documented around Luzon. Badlit is a related Visayan writing tradition associated with areas such as Cebu and Bohol. They share an Indic ancestry and similar syllabic principles, but their letterforms and regional histories differ."],
  ["Are Baybayin fonts free to use?", "Some are released under open licenses and others have limits on commercial use. Our fonts page links to license information and encourages checking the included license file before publishing a logo, product, or paid design."],
  ["How accurate is this translator?", "It is designed for careful phonetic conversion and common Tagalog patterns, but language always requires judgment. English names, dialects, and historical spelling conventions can have more than one reasonable result. Treat the Latin transcription as a transparent guide and consult a fluent reader for permanent work."],
];

const appSchema = { "@context": "https://schema.org", "@type": "WebApplication", name: "Baybayin Translator", url: "https://baybayintranslate.com/", applicationCategory: "EducationalApplication", operatingSystem: "Any", offers: { "@type": "Offer", price: "0", priceCurrency: "USD" }, description: "A free browser-based English and Tagalog to Baybayin translator with PNG and SVG downloads." };
const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faq.map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) };

export default function Home() {
  const chars = [["ᜀ","a"],["ᜁ","i/e"],["ᜂ","u/o"],["ᜃ","ka"],["ᜄ","ga"],["ᜅ","nga"],["ᜆ","ta"],["ᜇ","da/ra"],["ᜈ","na"],["ᜉ","pa"],["ᜊ","ba"],["ᜋ","ma"],["ᜌ","ya"],["ᜎ","la"],["ᜏ","wa"],["ᜐ","sa"],["ᜑ","ha"]];
  return <><Header /><main>
    <section className="hero"><div className="hero-copy"><p className="eyebrow">The script of our ancestors, in your hands</p><h1>Baybayin<br/><em>Translator</em></h1><div className="gold-line"/><p>Instantly convert English and Tagalog into the ancient Filipino script — beautifully, accurately, and privately.</p><a href="#translator" className="primary-button">Start translating <span>↓</span></a><small>No sign-up · Works offline · Free forever</small></div><div className="hero-art" aria-hidden="true"><span>ᜊ</span><span>ᜌ</span><span>ᜊᜌᜒᜈ᜔</span><i/><i/><i/><p>baybayin</p></div></section>
    <section id="translator" className="translator-section"><div className="section-heading"><p className="eyebrow">Write in Baybayin</p><h2>Translate words into living history</h2><p>Type a name, phrase, or idea. See every syllable become Baybayin as you write.</p></div><Translator /></section>
    <section className="learn-section"><div className="section-heading left"><p className="eyebrow">Discover the script</p><h2>Learn Baybayin — the ancient script of the Philippines</h2></div><div className="feature-grid"><article className="feature-card history-card"><span className="card-number">01</span><div className="card-icon">⌁</div><h3>What is Baybayin?</h3><p>Meet the precolonial writing system that carried poetry, trade, and memory across the islands.</p><a href="/learn/baybayin-history">Explore its history →</a></article><article className="feature-card alphabet-card"><span className="card-number">02</span><div className="mini-alphabet">{chars.slice(0,9).map(([char,latin])=><span key={latin} data-latin={latin}>{char}</span>)}</div><h3>The Baybayin alphabet</h3><p>Seventeen core signs. Three vowel sounds. One elegant system.</p><a href="/learn">Study every character →</a></article><article className="feature-card variants-card"><span className="card-number">03</span><div className="island-lines">ᜃ ᜊ ᜑ</div><h3>Regional scripts</h3><p>Travel from Badlit and Kulitan to the living traditions of Hanunoo and Tagbanwa.</p><a href="/sulat/badlit">Compare the variants →</a></article><article className="feature-card modern-card"><span className="card-number">04</span><div className="tattoo-line">ᜋᜑᜎ᜔</div><h3>Baybayin today</h3><p>Explore thoughtful tattoos, identity, lettering, and modern Filipino design.</p><a href="/tattoo">Create a tattoo preview →</a></article></div></section>
    <section className="story-section"><div className="story-aside"><span>ᜊᜌ᜔ᜊᜌᜒᜈ᜔</span><p>“To spell, to trace”</p></div><div className="story-copy"><p className="eyebrow">A writing system, not an alphabet</p><h2>How Baybayin carries sound</h2><p>Baybayin is an abugida, a family of scripts in which consonants arrive with a built-in vowel. The character ᜃ is read <em>ka</em>. Add a mark above and it becomes <em>ki</em> or <em>ke</em>; place the mark below and it becomes <em>ku</em> or <em>ko</em>. This compact logic lets a small set of graceful forms represent hundreds of spoken syllables.</p><p>That is why a good Baybayin translator follows pronunciation, not spelling. English words often need to be heard and adapted before they can be written. “Michael,” for example, should be broken into the sounds a Filipino speaker intends, not copied letter by letter. Our conversion engine exposes the Latin syllables beneath every character so you can see the decision instead of accepting a mysterious result.</p><a href="/learn/write-your-name">Learn the three writing rules →</a></div></section>
    <section className="guide-section"><div className="section-heading left"><p className="eyebrow">A clear, careful process</p><h2>How to use the Baybayin translator</h2></div><div className="steps"><article><span>1</span><h3>Write what you want to say</h3><p>Enter English, Tagalog, a personal name, or a short phrase. Auto detect looks for common Tagalog patterns while preserving punctuation and spaces.</p></article><article><span>2</span><h3>Read the sound guide</h3><p>Hover over each Baybayin sign to reveal its Latin sound. Adjust the original spelling if you want a different pronunciation.</p></article><article><span>3</span><h3>Save, share, or keep learning</h3><p>Copy the text, export a transparent PNG or editable SVG, or move your phrase into the tattoo previewer.</p></article></div></section>
    <section className="comparison-section"><div><p className="eyebrow">One archipelago, many scripts</p><h2>Baybayin and its Filipino relatives</h2><p>Baybayin belongs to a broad family of Brahmic-derived writing systems that moved through maritime Southeast Asia. The better-known Tagalog forms are only part of the story. Kapampangan Kulitan uses a distinctive arrangement and developed its own modern revival. Badlit refers to related Visayan traditions. Hanunoo and Tagbanwa are not merely museum subjects: communities in Mindoro and Palawan have continued writing related scripts into the present.</p><p>These traditions should not be flattened into one decorative “Filipino font.” Each belongs to particular communities, histories, and writing practices. Our regional guides introduce those differences and link directly to the others so learners can compare forms with respect.</p></div><div className="script-list"><a href="/sulat/badlit"><span>01</span><strong>Badlit</strong><small>Visayas</small>→</a><a href="/sulat/kulitan"><span>02</span><strong>Kulitan</strong><small>Pampanga</small>→</a><a href="/sulat/hanunoo"><span>03</span><strong>Hanunoo</strong><small>Mindoro</small>→</a><a href="/sulat/tagbanwa"><span>04</span><strong>Tagbanwa</strong><small>Palawan</small>→</a></div></section>
    <section className="faq-section"><div className="section-heading"><p className="eyebrow">Questions, answered</p><h2>Baybayin translator FAQ</h2></div><div className="faq-list">{faq.map(([q,a],i)=><details key={q} open={i===0}><summary><span>{String(i+1).padStart(2,"0")}</span>{q}<b>+</b></summary><p>{a}</p></details>)}</div></section>
    <section className="final-cta"><span className="watermark">ᜊ</span><p className="eyebrow">Your words, another way</p><h2>Write something worth remembering.</h2><p>Turn a name, a promise, or a piece of home into Baybayin.</p><a href="#translator" className="primary-button">Open the translator ↑</a></section>
  </main><Footer /><Script id="app-schema" type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(appSchema)}}/><Script id="faq-schema" type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqSchema)}}/></>;
}
