"use client";
import { useEffect, useMemo, useState } from "react";
import { transliterate } from "../components/Translator";

const styles = [["ink","Traditional ink","Classic and bold"],["tribal","Tribal / geometric","Angular framing"],["watercolor","Watercolor","Soft pigment wash"],["minimal","Minimalist line","Quiet and precise"]];
export default function TattooStudio(){
 const [text,setText]=useState("Mahal kita"); const [style,setStyle]=useState("ink"); const [tone,setTone]=useState("warm"); const script=useMemo(()=>transliterate(text).map(u=>u.script).join(""),[text]);
 useEffect(()=>{const q=new URLSearchParams(location.search).get("text");if(q)setText(q.slice(0,100))},[]);
 function download(){const c=document.createElement("canvas");c.width=1800;c.height=1000;const x=c.getContext("2d")!;x.fillStyle=tone==="deep"?"#8c593c":tone==="light"?"#e4b990":"#bf8962";x.fillRect(0,0,c.width,c.height);x.fillStyle="#1d130f";x.font="150px 'Noto Sans Tagalog',sans-serif";x.textAlign="center";x.textBaseline="middle";x.fillText(script,900,500,1500);c.toBlob(b=>{if(!b)return;const a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="baybayin-tattoo-preview.png";a.click()},"image/png")}
 return <section className="tattoo-studio"><div className="tattoo-controls"><label><span>Words to preview</span><input value={text} onChange={e=>setText(e.target.value)} maxLength={100}/></label><div><span>Tattoo style</span><div className="style-options">{styles.map(([id,name,note])=><button key={id} onClick={()=>setStyle(id)} className={style===id?"active":""}><i className={`sample-${id}`}>ᜊ</i><b>{name}</b><small>{note}</small></button>)}</div></div><label><span>Skin preview</span><select value={tone} onChange={e=>setTone(e.target.value)}><option value="light">Light</option><option value="warm">Warm</option><option value="deep">Deep</option></select></label></div><div className={`skin-preview skin-${tone} tattoo-${style}`}><div className="tattoo-render">{script}</div><span>Preview only — always verify before tattooing</span></div><div className="studio-actions"><button onClick={download}>↓ Download skin preview</button><a href={`/?text=${encodeURIComponent(text)}#translator`}>Review translation →</a></div></section>
}
